doctrine:
    dbal:
        driver: pdo_mysql
        host: "%env(APP_DB_HOST)%"
        port: "%env(APP_DB_PORT)%"
        dbname: "%env(APP_DB_NAME)%"
        user: "%env(APP_DB_USER)%"
        password: "%env(APP_DB_PASSWORD)%"
        charset:  UTF8
        server_version: '%env(APP_DB_VERSION)%'
        schema_filter: '~^(?!system_)~'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
