version: "3.4"

services:
###> doctrine/doctrine-bundle ###
  mysql80:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'foobar'
    ports:
      - "10108:3306"
    volumes:
      - data_mysql80:/var/lib/mysql
    command: ["mysqld", "--max-allowed-packet=536870912"]
###< doctrine/doctrine-bundle ###

  php:
    build:
      context: .
      target: app_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - mysql80
    environment:
      MAKER_PHP_CS_FIXER_BINARY_PATH: '/srv/app/vendor/bin/php-cs-fixer'
      MAKER_PHP_CS_FIXER_CONFIG_PATH: '.php-cs-fixer.php'

  caddy:
    build:
      context: .
      target: app_caddy
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

volumes:
  php_socket:
  caddy_data:
  caddy_config:
  data_mysql80:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
